# Generated by Django 5.2.8 on 2025-11-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_auto_20251109_2309"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proveedor",
            name="contacto",
        ),
    ]
