# Generated by Django 5.2.8 on 2025-11-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0003_remove_proveedor_contacto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proveedor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="proveedor",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="proveedor",
            name="fecha_registro",
        ),
        migrations.AddField(
            model_name="proveedor",
            name="contacto",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
