# Generated by Django 5.2.8 on 2025-11-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0005_alter_venta_total_ventadetalle"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="tipo",
            field=models.CharField(
                choices=[("venta", "Venta"), ("devolucion", "Devolución")],
                default="venta",
                max_length=20,
            ),
        ),
    ]
